project:
  output-dir: ../../_book/en

lang: en-CA

cit-title: |
  Do what you think is interesting,  
  do something that you think is fun and worthwhile,  
  because otherwise you won’t do it well anyway.
cit-author: Brian W. Kernighan

book:
  title: "On the R-way to hell"
  subtitle: "Statistical analysis in the marvelous world of R"
  description: "Early version needed to be severely updated/modified"
  author: Julien Martin

  page-footer:
    left: |
      <a href="https://biostats-uottawa.github.io/people.html">Julien Martin</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  navbar:
    background: light
    collapse-below: lg
    title: '![](images/cover/book_hex_en.png){width="50px"} R Way'
    left:
      - text: Data
        href: 902-data-files.qmd
      - text: Other resources
        menu:
          - text: 'Biostats uOttawa'
            href: https://biostats-uottawa.github.io/
          - text: Biostats with R (Bio4158)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Biostats avec R (Bio4558)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: Advanced biostats and open science (Bio8940)
            href: https://biostats-uottawa.github.io/bio8940_course/

    right:
      - icon: flag
        menu:
        - href: ../fr
          text: Français
#        - href: ../es
#          text: Español

  cover-image: images/cover/cover_en.png
  chapters:
    - index.qmd
    - part: Using R
      chapters:
        - 01-start.qmd
        - 02-basics.qmd
        - 03-data.qmd
        - 04-graphics_short.qmd
        - 05-programming.qmd
        - 06-quarto.qmd
        - 07-github.qmd
    - part: Fundamentals of stats
#      chapters:
#        - 21-distributions, p CI.qmd

    - part: Linear models
      chapters:
        - 11-stats.qmd
#        - 22-glm.qmd
    - part: Generalized linear models
#      chapters:
#        - 31-principles.qmd
#        - 31-poisson.qmd
#        - 31-binomial.qmd
    - part: Mixed models
#      chapters:
#        - 31-principles.qmd
#        - 31-lme.qmd
#        - 32-glme.qmd
#        - 33-multi_lme.qmd
    - part: Generalized additive models
#        - 41-gam.qmd
    - part: Multivariate analysis
#        - 51-acp.qmd
#        - 52-overview others.qmd
    - part: Bayesian approach
#        - 61-intro to Bayesian.qmd
#        - 62-lm-brms.qmd
#        - 63-lme-brms.qmd
#        - 64-gam-brms.qmd
    - 901-references.qmd
  appendices:
    - 902-data-files.qmd
    - 903-latex.qmd
