project:
  output-dir: _book/en

lang: en-CA

cit-title: |
  Do what you think is interesting,  
  do something that you think is fun and worthwhile,  
  because otherwise you won’t do it well anyway.
cit-author: Brian W. Kernighan

book:
  title: "On the R-way to hell"
  subtitle: "An introduction to the marvelous world of R"
  description: "Early version needed to be severely updated/modified"
  author: Julien Martin

  page-footer:
    left: |
      <a href="https://biostats-uottawa.github.io/people.html">Julien Martin</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  navbar:
    background: light
    collapse-below: lg
    title: R Way
    left:
      - text: Data
        href: 92-data-files.qmd
      - text: Other resources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Biostats with R (Bio4158)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Biostats avec R (Bio4558)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: Advanced biostats and open science (Bio8940)
            href: https://biostats-uottawa.github.io/bio8940_course/

    right:
      - icon: flag
        menu:
        - href: ../fr
          text: Français
#        - href: ../es
#          text: Español

  cover-image: images/cover/cover_en.png
  chapters:
    - index.qmd
    - part: Starting with R
      chapters:
        - 01-start.qmd
        - 02-basics.qmd
    - part: Data and graphics
      chapters:
        - 11-data.qmd
        - 12-graphics_short.qmd
    - part: Linear models
      chapters:
        - 21-stats.qmd
#        - 22-glm.qmd
    - part: Mixed models
#      chapters:
#        - 31-lme.qmd
#        - 32-glme.qmd
#        - 33-multi_lme.qmd
    - part: Generalized additive models
#        - 41-gam.qmd
    - part: Multivariate analysis
#        - 51-acp.qmd
#        - 52-overview others.qmd
    - part: Bayesian approach
#        - 61-intro to Bayesian.qmd
#        - 62-lm-brms.qmd
#        - 63-lme-brms.qmd
#        - 64-gam-brms.qmd
    - part: Programming and writing with R
      chapters:
        - 81-programming.qmd
        - 82-rmarkdown.qmd
        - 83-github.qmd
    - 91-references.qmd
  appendices:
    - 92-data-files.qmd
    - 93-latex.qmd
