project:
  type: book
  output-dir: _book

execute: 
  cache: true
  freeze: auto

book:
  google-analytics: G-6LLMGL3T2Q
  title: "On the R-way to hell"
  subtitle: "An introduction to the marvelous world of R"
  description: "Early version needed to be severely updated/modified"
  author: <a href="https://biostats-uottawa.github.io/people.html">Julien Martin</a>
  date: today
  date-format: iso 
  reader-mode: true
  search: true
  page-footer:
    left: |
      <a href="https://biostats-uottawa.github.io/people.html">Julien Martin</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover_introR.jpg
  favicon: cover.jpg
  site-url: https://biostats-uottawa.github.io/R_way/
  repo-url: https://github.com/biostats-uottawa/R_way/
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  navbar:
    background: light
#    logo: quarto.png
#    logo-alt: "Quarto logo."
    collapse-below: lg
    title: "R Way"
    left:
      - text: Slides
        href: https://biostats-uottawa.github.io/intro_r_en.html/#slides 
      - text: Data
        href: https://biostats-uottawa.github.io/intro_r_en.html/#data
      - text: Other resources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Bio4158 (english)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Bio4558 (français)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: Chemin de l'enf-R
            href: https://biostats-uottawa.github.io/intro_r_fr.html

  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-basics.qmd
    - 03-data.Rmd
    - 04-graphics_short.qmd
    - 05-stats.qmd
    - 06-programming.Rmd
    - 07-rmarkdown.qmd
    - 08-github.Rmd
    - 98-references.qmd
  appendices:
    - 99-Appendix.Rmd

bibliography: [book.bib, grateful-refs.bib]
biblio-style: apalike
csl: ecology.csl

format:
  html:
    theme:
      light: cosmo #, css/theme.scss]
      dark: [cosmo, css/theme-dark.scss]
    css: css/style.css
    code-link: true

    author-meta: "Julien Martin"
    callout-appearance: simple

  pdf:
    documentclass: scrbook
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    toc-depth: 2

  epub:
    dev: svglite
    stylesheet: css/epub.css
    toc: true

editor: visual