project:
  output-dir: _book/fr

lang: fr-fr
language:
  tools-download: "Télécharger"

cit-title: |
  Faites ce que vous pensez être intéressant,  
  faites quelque chose que vous pensez être utile et amusant,  
  parce que sinon, vous ne le ferez pas bien de toute façon.
cit-author: Brian W. Kernighan

book:
  title: "Sur le chemin de l'enf-R"
  subtitle: "Une introduction au monde merveilleux de R"
  description: "En cours de traduction"
  author: Julien Martin

  page-footer:
    left: |
      <a href="https://biostats-uottawa.github.io/people.html">Julien Martin</a>
    right: |
      Ce livre a été crée avec <a href="https://quarto.org/">Quarto</a>.

  navbar:
    background: light
    collapse-below: lg
    title: "Chemin enf-R"
    left:
      - text: Données
        href: 92-fichiers-donnees.qmd
      - text: Autres ressources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Biostats with R (Bio4158)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Biostats avec R (Bio4558)
            href: https://biostats-uottawa.github.io/bio4558_cours/
          - text: Biostats avancées et science ouverte (Bio8940)
            href: https://biostats-uottawa.github.io/bio8940_course/

    right:
      - icon: flag
        menu:
        - href: ../en
          text: English
#        - href: ../es
#          text: Español

  cover-image: images/cover/cover_fr.png
  
  chapters:
    - index.qmd
    - part: Débuter avec R
      chapters:
        - 01-debut.qmd
#        - 02-basics.qmd
    - part: Données et graphiques
#      chapters:
#        - 11-data.qmd
#        - 12-graphics_short.qmd
    - part: Modèles linéaires
#      chapters:
#        - 21-stats.qmd
#        - 22-glm.qmd
    - part: Modèles mixtes
#      chapters:
#        - 31-lme.qmd
#        - 32-glme.qmd
#        - 33-multi_lme.qmd
    - part: Modèles additifs (gam)
#        - 41-gam.qmd
    - part: Analyse multivariées
#        - 51-acp.qmd
#        - 52-overview others.qmd
    - part: Approche Bayesienne
#        - 61-intro to Bayesian.qmd
#        - 62-lm-brms.qmd
#        - 63-lme-brms.qmd
#        - 64-gam-brms.qmd
    - part: Programmation et écriture avec R
#      chapters:
#        - 81-programming.qmd
#        - 82-rmarkdown.qmd
#        - 83-github.qmd
    - 91-bibliographie.qmd
  appendices:
    - 92-fichiers-donnees.qmd
#    - 93-latex.qmd